# A redirect rule which routes Netlify [.com extension] to Custom Domain.
[[redirects]]
    from = "https://quizzical-lewin-a6c5f1.netlify.com/"
    to = "https://www.studiobarberio.org/"
    status = 301

# A redirect rule which routes Netlify [new .app extension] to Custom Domain.
[[redirects]]
    from = "https://quizzical-lewin-a6c5f1.netlify.app/"
    to = "https://www.studiobarberio.org/"
    status = 301

# A redirect rule for old Wordpress website urls.
[[redirects]]
    from = "/it/*"
    to = "/"
    status = 301

# A redirect rule for old Wordpress website urls.
[[redirects]]
    from = "/en/*"
    to = "/en/"
    status = 301

# Headers to return with requests for the specified paths
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    # Multi-key header rules are expressed with multi-line strings.
    cache-control = '''
      max-age=360000,
      no-cache,
      no-store,
      must-revalidate'''

# Asset optimization, mimicking what we accomplished earlier
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true