backend:
  name: github
  repo: uptheirons78/studio-legale-barberio

media_folder: static/assets
public_folder: /assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data di pubblicazione", name: "date", widget: "datetime" }
      - { label: "Descrizione", name: "description", widget: "string" }
      - { label: "Categoria",
          name: "category",
          widget: "select",
          options: ["sentenza", "articolo"],
          default: "articolo"
        }
      - { label: "Sentenza", name: "sentenza", widget: "file", required: false }
      - { label: "Testo Pulsante Sentenza", name: "sentenza_btn", widget: "string", required: false }
      - { label: "Link Articolo",
          name: "link",
          widget: "string",
          required: false,
          hint: "Aggiungere qui il link ad un articolo esterno al sito quando serve"
        }
      - { label: "Testo Pulsante Articolo", name: "articolo_btn", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pagine"
    files:
      - file: "content/pages/home/index.md"
        label: "Home"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Descrizione", name: "description", widget: "string"}
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/pages/home/en-index.md"
        label: "Home EN"
        name: "en-index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "en-index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/pages/chi-siamo/index.md"
        label: "Chi Siamo"
        name: "chi-siamo"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "chi-siamo"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Descrizione", name: "description", widget: "string"}
          - { name: "body", label: "Body", widget: "markdown" }
          - {
              label: "Il Nostro Team",
              name: "members",
              widget: "object",
              fields:
                [
                  {
                    label: "Collaboratori Interni",
                    name: "collaboratori",
                    widget: "list",
                    fields:
                      [
                        { label: "Nome", name: "name", widget: "string" },
                        { label: "Foto", name: "image", widget: "image" },
                        { label: "Descrizione Foto", name: "imageAlt", widget: "string" },
                        { label: "Occupazione", name: "occupazione", widget: "string" },
                        { label: "Work", name: "work", widget: "string" },
                        { label: "Descrizione", name: "descrizione", widget: "string" },
                        { label: "Description", name: "description", widget: "string" },
                        { label: "Telefono", name: "telefono", widget: "string" },
                        { label: "Email", name: "email", widget: "string" },
                      ],
                  },
                ],
            }
      - file: "content/pages/chi-siamo/en-index.md"
        label: "About Us"
        name: "about-us"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-us"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Descrizione", name: "description", widget: "string"}
          - { name: "body", label: "Body", widget: "markdown" }
      - file: "content/pages/blog/index.md"
        label: "Blog"
        name: "blog-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-page"}
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Titolo Header", name: "heading", widget: "string"}
          - {label: "Descrizione", name: "description", widget: "string"}
          - { name: "body", label: "Body", widget: "markdown" }
      - file: "content/pages/sentenze/index.md"
        label: "Sentenze"
        name: "sentenze-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "sentenze-page"}
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Titolo Header", name: "heading", widget: "string"}
          - {label: "Descrizione", name: "description", widget: "string"}
          - { name: "body", label: "Body", widget: "markdown" }
      - file: "content/pages/collaboratori/index.md"
        label: "Collaboratori"
        name: "collaboratori-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "collaboratori-page"}
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Titolo EN", name: "en-title", widget: "string"}
          - {label: "Titolo Header", name: "heading", widget: "string"}
          - {label: "Titolo Header EN", name: "en-heading", widget: "string"}
          - {label: "Descrizione", name: "description", widget: "string"}
          - {label: "Descrizione EN", name: "en-description", widget: "string"}
          - { name: "body", label: "Body", widget: "markdown", required: false }
          - {
              label: "I Nostri Collaboratori",
              name: "collaboratori",
              widget: "object",
              fields:
                [
                  {
                    label: "Collaboratori Esterni",
                    name: "collaboratori-esterni",
                    widget: "list",
                    fields:
                      [
                        { label: "Nome", name: "name", widget: "string"},
                        { label: "Titolo", name: "titolo", widget: "string"},
                        { label: "Titolo EN", name: "en-titolo", widget: "string"},
                        { label: "Specializzazione", name: "specializzazione", widget: "string" },
                        { label: "Specializzazione EN", name: "en-specializzazione", widget: "string" },
                        { label: "Foro", name: "foro", widget: "string"},
                        { label: "Foro EN", name: "en-foro", widget: "string"},
                        { label: "Indirizzo", name: "indirizzo", widget: "string", required: false },
                        { label: "Telefono", name: "telefono", widget: "string", required: false },
                        { label: "Email", name: "email", widget: "string", required: false },
                        { label: "Website", name: "website", widget: "string", required: false },
                        { label: "Description", name: "description", widget: "text"}
                        { label: "Description EN", name: "en-description", widget: "text"}
                      ],
                  },
                ],
            }
      - file: "content/pages/contatti/index.md"
        label: "Contatti"
        name: "contatti-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contatti-page"}
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Titolo Header", name: "heading", widget: "string"}
          - {label: "Descrizione", name: "description", widget: "string"}
          - { name: "body", label: "Body", widget: "markdown" }
      - file: "content/pages/contatti/en-index.md"
        label: "Contact Us"
        name: "contact-us"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-us"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "heading", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - { name: "body", label: "Body", widget: "markdown" }
      - file: "content/pages/privacy/index.md"
        label: "Privacy Policy"
        name: "privacy-policy"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "privacy-policy"}
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Titolo Header", name: "heading", widget: "string"}
          - {label: "Descrizione", name: "description", widget: "string"}
          - { name: "body", label: "Body", widget: "markdown" }
      - file: "content/pages/cookies/index.md"
        label: "Cookies Policy"
        name: "cookies-policy"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cookies-policy"}
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Titolo Header", name: "heading", widget: "string"}
          - {label: "Descrizione", name: "description", widget: "string"}
          - { name: "body", label: "Body", widget: "markdown" }
      - file: "content/pages/laura/index.md"
        label: "Laura"
        name: "laura"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "laura-page"}
          - {label: "Title", name: "title", widget: "string"}
          - { name: "body", label: "Body", widget: "markdown" }
      - file: "content/pages/laura/en-index.md"
        label: "Laura EN"
        name: "en-laura"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "en-laura-page"}
          - {label: "Title", name: "title", widget: "string"}
          - { name: "body", label: "Body", widget: "markdown" }
      - file: "content/pages/sara/index.md"
        label: "Sara"
        name: "sara"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "sara-page"}
          - {label: "Title", name: "title", widget: "string"}
          - { name: "body", label: "Body", widget: "markdown" }
      - file: "content/pages/sara/en-index.md"
        label: "Sara EN"
        name: "en-sara"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "en-sara-page"}
          - {label: "Title", name: "title", widget: "string"}
          - { name: "body", label: "Body", widget: "markdown" }
